"""7th migration"""
# Generated by Django 4.2.1 on 2023-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    7th migration
    """
    dependencies = [
        ('blog', '0006_alter_post_author_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique_for_date='published'),
        ),
    ]
