# Generated by Django 4.2.1 on 2023-07-02 14:23
"""11th migration"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """11th migration"""
    dependencies = [
        ('blog', '0010_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
