# Generated by Django 4.2.1 on 2023-07-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_photocontestsubmission_contestsubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContestSubmission',
            new_name='PhotoContestSubmission',
        ),
    ]
